export const metadata = {
  title: "Privacy Policy | DevRoast",
  description: "Privacy Policy for DevRoast, the GitHub Developer Report Card.",
};

export default function PrivacyPolicy() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-16 sm:py-24">
      <h1 className="mb-8 text-3xl font-black tracking-tight text-text-primary sm:text-4xl">
        Privacy Policy
      </h1>
      
      <div className="prose prose-invert max-w-none text-text-secondary">
        <p className="mb-6">
          <strong>Effective Date:</strong> {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
        </p>

        <p className="mb-6">
          Welcome to <strong>DevRoast</strong> ("we", "our", or "us"). We are committed to protecting your privacy. This Privacy Policy explains how we collect, use, and handle information when you use our website and services.
        </p>

        <h2 className="mt-10 mb-4 text-xl font-bold text-text-primary">1. Information We Collect</h2>
        <ul className="mb-6 list-disc pl-5 space-y-2">
          <li>
            <strong>GitHub Public Data:</strong> When you enter a GitHub username, we fetch public data associated with that profile from the official GitHub API. This includes public repositories, bio, follower counts, and language statistics. We <strong>do not</strong> access private repositories or private profile data.
          </li>
          <li>
            <strong>Usage Data (Analytics):</strong> We use Vercel Analytics to collect anonymous, aggregated data about website traffic (such as page views, browser types, and referring sites) to improve our service.
          </li>
          <li>
            <strong>IP Addresses for Rate Limiting:</strong> We temporarily process IP addresses in memory to enforce rate limiting (preventing abuse and API spam). These IP addresses are not permanently stored in any database.
          </li>
        </ul>

        <h2 className="mt-10 mb-4 text-xl font-bold text-text-primary">2. How We Use the Information</h2>
        <p className="mb-6">We use the collected information solely for the following purposes:</p>
        <ul className="mb-6 list-disc pl-5 space-y-2">
          <li>To generate your DevRoast report card and calculate your developer score.</li>
          <li>To provide public profile statistics to large language models (LLMs), such as Groq/Llama 3, for the sole purpose of generating a customized, humorous "roast" text.</li>
          <li>To ensure the security of our service and prevent abusive automated requests.</li>
        </ul>

        <h2 className="mt-10 mb-4 text-xl font-bold text-text-primary">3. Third-Party Services</h2>
        <p className="mb-6">We rely on third-party services to operate DevRoast. By using our service, you acknowledge that your data may be processed by:</p>
        <ul className="mb-6 list-disc pl-5 space-y-2">
          <li><strong>GitHub API:</strong> Used to fetch the public developer data.</li>
          <li><strong>Groq:</strong> Used to generate the AI roasts based on the fetched public data. Note: We only send aggregated public stats to Groq; we do not send any personally identifiable information beyond what is already public on GitHub.</li>
          <li><strong>Vercel:</strong> Used for hosting our application and providing anonymous web analytics.</li>
        </ul>

        <h2 className="mt-10 mb-4 text-xl font-bold text-text-primary">4. Data Storage and Retention</h2>
        <p className="mb-6">
          <strong>We do not store your GitHub data.</strong> Every report is generated dynamically on the fly. We do not maintain a database of scanned profiles, nor do we store the generated roasts permanently. Rate-limiting IP data is held temporarily in memory and is automatically discarded.
        </p>

        <h2 className="mt-10 mb-4 text-xl font-bold text-text-primary">5. Cookies and Tracking</h2>
        <p className="mb-6">
          DevRoast does not use tracking cookies for advertising or personal identification. We only use anonymous telemetry (Vercel Analytics) to understand general website performance.
        </p>

        <h2 className="mt-10 mb-4 text-xl font-bold text-text-primary">6. Disclaimer</h2>
        <p className="mb-6">
          DevRoast is intended for entertainment purposes. The "roasts" are generated by artificial intelligence and should not be taken seriously. We are not affiliated with, endorsed by, or sponsored by GitHub, Microsoft, or Groq.
        </p>

        <h2 className="mt-10 mb-4 text-xl font-bold text-text-primary">7. Contact</h2>
        <p className="mb-6">
          If you have any questions or concerns about this Privacy Policy, or if you would like to request the removal of your public data from being accessible via our app, please contact the maintainer through the GitHub repository associated with this project.
        </p>
      </div>
      
      <div className="mt-12 text-center">
        <a href="/" className="text-sm font-medium text-accent hover:underline">
          &larr; Back to Home
        </a>
      </div>
    </div>
  );
}
